version: '3.8'
services:
  anime-sonarr:
    image: linuxserver/sonarr
    container_name: anime-sonarr
    environment:
      - PUID=1000 # Adjust as needed
      - PGID=1000 # Adjust as needed
      - TZ=Asia/Manila
    volumes:
      - ./anime-sonarr/config:/config
      - $MEDIA_PATH:/media/Anime
      - ./downloads:/downloads
    ports:
      - 9898:8989
    restart: unless-stopped

  anime-decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: anime-decluttarr
    environment:
      - TZ=Asia/Manila
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=INFO
      - REMOVE_TIMER=10
      - REMOVE_FAILED=True
      - REMOVE_FAILED_IMPORTS=True
      - REMOVE_METADATA_MISSING=True
      - REMOVE_MISSING_FILES=True
      - REMOVE_ORPHANS=True
      - REMOVE_SLOW=True
      - REMOVE_STALLED=True
      - REMOVE_UNMONITORED=True
      - CANCEL_UNAVAILABLE_FILES=True
      - MIN_DOWNLOAD_SPEED=100
      - PERMITTED_ATTEMPTS=3
      - NO_STALLED_REMOVAL_QBIT_TAG=Don't Kill
      - IGNORE_PRIVATE_TRACKERS=True
      - FAILED_IMPORT_MESSAGE_PATTERNS=["Not an upgrade for existing", "Not a Custom Format upgrade for existing"]
      - RADARR_URL=http://$LOCAL_IP:7878
      - RADARR_KEY=$RADARR_API_KEY
      - SONARR_URL=http://$LOCAL_IP:8989
      - SONARR_KEY=$SONARR_API_KEY
      - QBITTORRENT_URL=http://$LOCAL_IP:8080
    restart: always

  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    environment:
      - TZ=Asia/Manila
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=INFO
      - REMOVE_TIMER=10
      - REMOVE_FAILED=True
      - REMOVE_FAILED_IMPORTS=True
      - REMOVE_METADATA_MISSING=True
      - REMOVE_MISSING_FILES=True
      - REMOVE_ORPHANS=True
      - REMOVE_SLOW=True
      - REMOVE_STALLED=True
      - REMOVE_UNMONITORED=True
      - CANCEL_UNAVAILABLE_FILES=True
      - MIN_DOWNLOAD_SPEED=100
      - PERMITTED_ATTEMPTS=3
      - NO_STALLED_REMOVAL_QBIT_TAG=Don't Kill
      - IGNORE_PRIVATE_TRACKERS=True
      - FAILED_IMPORT_MESSAGE_PATTERNS=["Not an upgrade for existing", "Not a Custom Format upgrade for existing"]
      - RADARR_URL=http://$LOCAL_IP:7878
      - RADARR_KEY=$RADARR_API_KEY
      - SONARR_URL=http://$LOCAL_IP:8989
      - SONARR_KEY=$SONARR_API_KEY
      - LIDARR_URL=http://$LOCAL_IP:8686
      - LIDARR_KEY=$LIDARR_API_KEY
      - READARR_URL=http://$LOCAL_IP:8787
      - READARR_KEY=$READARR_API_KEY
      - WHISPARR_URL=http://$LOCAL_IP:6969
      - WHISPARR_KEY=$WHISPARR_API_KEY
      - QBITTORRENT_URL=http://$LOCAL_IP:8080
    restart: always

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000 # Adjust as needed
      - PGID=1000 # Adjust as needed
      - TZ=Asia/Manila
    volumes:
      - ./lidarr/config:/config
      - $MEDIA_PATH:/media/Music
      - ./downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000 # Adjust as needed
      - PGID=1000 # Adjust as needed
      - TZ=Asia/Manila
    volumes:
      - ./radarr/config:/config
      - $MEDIA_PATH:/media/Movies
      - ./downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000 # Adjust as needed
      - PGID=1000 # Adjust as needed
      - TZ=Asia/Manila
    volumes:
      - ./sonarr/config:/config
      - $MEDIA_PATH:/media/Series
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000 # Adjust as needed
      - PGID=1000 # Adjust as needed
      - TZ=Asia/Manila
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - PUID=1000 # Adjust as needed
      - PGID=1000 # Adjust as needed
      - TZ=Asia/Manila
    volumes:
      - ./homarr/config:/app/data/configs
    ports:
      - 7575:7575
    restart: unless-stopped
