version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"  # Jellyfin web interface
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - jellyfin-media:/media
    user: "1000:1000"  # Adjust as needed
    restart: unless-stopped

  jellyseer:
    image: jellyseer/jellyseer
    container_name: jellyseer
    ports:
      - "8196:8196"  # Jellyseer web interface
    environment:
      - JELLYFIN_URL=http://jellyfin:8096
      - JELLYFIN_API_KEY=your_jellyfin_api_key_here
    depends_on:
      - jellyfin
    user: "1000:1000"  # Adjust as needed
    restart: unless-stopped

volumes:
  jellyfin-config:
  jellyfin-cache:
  jellyfin-media:
