version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096 # Jellyfin web interface
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./jellyfin/media:/media
    environment:
      - TZ=Asia/Manila
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
  jellyseer:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseer
    ports:
      - 8196:5055 # Jellyseer web interface
    volumes:
      - ./jellyseer/config:/app/config
    environment:
      - JELLYFIN_URL=http://jellyfin:8096
      - JELLYFIN_API_KEY=your_jellyfin_api_key_here
      - TZ=Asia/Manila
      - PUID=1000
      - PGID=1000
    depends_on:
      - jellyfin
    restart: unless-stopped
